# Generated by Django 5.0.3 on 2024-04-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_facebook_user_languages_user_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(default='Notification', max_length=255),
        ),
    ]
