# Generated by Django 5.0.3 on 2024-06-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
    ]
