# Generated by Django 5.0.3 on 2024-06-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_occupation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
